name: nginx
version: stable 
replicaCount: 1
image:
  repository: "senthilnathanam/nginx-realip"
  pullPolicy: "IfNotPresent"
  tag: "v1.0.0_23"
service:
  type: ClusterIP
  port: 80
envName: DOMAIN_NAME
configName: env
configValue: DOMAIN_NAME
