FROM nginx:stable-alpine
COPY mysite.template /etc/nginx/conf.d/mysite.template
COPY sample1.html /usr/share/nginx/html/index.html
COPY nginx.conf /etc/nginx/nginx.conf
CMD ["/bin/sh" , "-c" , "envsubst '${DOMAIN_NAME}'< /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"]
